name: Update Declassified Map

on:
  schedule:
    - cron: "0 5 * * 1"   # Every Monday at 5am UTC
  workflow_dispatch:        # Manual trigger from GitHub Actions tab

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write       # Required to commit the updated files

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch available scenes and build map
        run: python fetch_and_build.py
        env:
          M2M_USERNAME: ${{ secrets.M2M_USERNAME }}
          M2M_TOKEN: ${{ secrets.M2M_TOKEN }}

      - name: Commit updated files
        run: |
          git config user.name  "declass-map-bot"
          git config user.email "bot@users.noreply.github.com"
          git add index.html available_scenes.geojson
          git diff --staged --quiet || git commit -m "Weekly update $(date -u +%Y-%m-%d): update available scenes"
          git push
